import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
		ArrayList<String> arrayList = new ArrayList<String>();
		
	}
}
